# print('file: DInormalPDF.R')
# print(date())
# print('3 = normal distribution (8/2022)')
mu = 3.1; sigma = 1 # true values
x = seq(mu-3*sigma,mu+3*sigma,sigma/50)
y = dnorm(x,mu,sigma)
# installl.packages('latex2exp')
library(latex2exp)
# png('NormalPDF4MC220829.png',width=16,height=16,units='cm',res=300)
plot(x,y,type='l',lwd=4,col='blue',xlab='x',ylab='y',las=1,cex=0.6,cex.lab=1.5)
abline(v=mu,lty=2,col='magenta',lwd=1)
text(0.5,0.35,TeX('$\\mu = 3.1$'),col='blue',pos=4,cex=1.5)
text(0.5,0.3,TeX('$\\sigma^2 = 1$'),col='blue',pos=4,cex=1.5)
# dev.off()