print('file: LookMultipleBoxPlot.R')
set.seed(1953) # set seed for random number generators
n1 = 30; r1 = rnorm(n1) # random number from standard normal distributions
n2 = 35; r2 = rnorm(n2)
n3 = 45; r3 = rnorm(n3)
n4 = 39; r4 = rnorm(n4)
# png('TransparentMultiBoxplot220220.png',width=16,height=16,units='cm',res=300)
boxplot(r1,r2,r3,r4,col='yellow',las=1)
jitter1 = rnorm(length(r1),1,0.05); points(jitter1,r1,col='blue',lwd=3,cex=0.4)
jitter2 = rnorm(length(r2),2,0.05); points(jitter2,r2,col='blue',lwd=3,cex=0.4)
jitter3 = rnorm(length(r3),3,0.05); points(jitter3,r3,col='blue',lwd=3,cex=0.4)
jitter4 = rnorm(length(r4),4,0.05); points(jitter4,r4,col='blue',lwd=3,cex=0.4)
# dev.off()
# ----------------------------------------------------------------
# Remarks: transparent boxplot for 4 data sets
# The 4 data sets are generated by random sampling from the standard normal distribution.
# boxplot()   can take several (here: 4) data sets
