print('file: ReadFromExcel.R')
# install.packages('readxl')
library(readxl)
mydata1 <- read_xlsx('Zar10Ex10d1x210223.xlsx')
mydata <- as.data.frame(mydata1)
q1 = mydata[mydata$group=='group1',]; weight1 = as.numeric(q1$weight)
q2 = mydata[mydata$group=='group2',]; weight2 = as.numeric(q2$weight)
q3 = mydata[mydata$group=='group3',]; weight3 = as.numeric(q3$weight)
q4 = mydata[mydata$group=='group4',]; weight4 = as.numeric(q4$weight)
# png('Zar10Ex10d1Boxplot210223.png',width=16,height=12,units='cm',res=300)
boxplot(weight1,weight2,weight3,weight4,col='blue',las=1)
# dev.off()
summary(aov(weight ~ group,data=mydata))
q = summary(aov(weight~group,data=mydata))
p = q[[1]][, 5][1]  # yes, this is obvious!
Fvalue = q[[1]][, 4][1]
print(c(round(p,5),' p'))
print(c(round(Fvalue,3),' Fvalue'))
print(q)